### ISSUE TITLE
تبدیل تقویم میلادی به خورشیدی در همه گزارش ها

### ISSUE THREAD

**Issue by mrr-r** [parodoo/parOdoo#17]
با سلام
من درباره تبدیل تقویم میلادی به خورشیدی در همه گزارش ها زیاد تحقیق کردم
و این مطلب را یافتم اگر کسی می تواند در این مورد کمک کند خوشحال می شوم در موارد دیگر شما را یاری کنم.من ماژول های زیادی دارم که فکر کنم به دردتون بخوره. 
این مطلبی است که من یافتم:

https://stackoverflow.com/questions/41525570/how-can-i-convert-gregorian-to-persian-jalali-date-in-all-odoo-pdf-repor

You just need to inherit the "value_to_html" method in both "DateConverter" and "DateTimeConverter" classes in ir_qweb.py and convert the input value to jalali date. You can use this link in case you need a python jalali date converter.(in \server\odoo\addons\base\models\ir_qweb_fields.py)

اگر کسی تونست کمکی کنه این ایمیل manovce@gmail.com بنده هست می تونیم همکاری کنیم ممنون!

**Comment by saeed-raeisi** [comment]
Hi this item
I added it before but still to the module
I did not transfer l10n_ir_base
https://github.com/OCA/l10n-iran

List the problems you have problems with and help with the localization project

Charts (done)
fullcalendar (done)
blog (done)
date picker (done)
Output date pdf (done)
Excel output date (on working)
Date of fiscal year (done)

**Comment by mrr-r** [comment]
Hello Mr. Raeisi
Thank you for helping the Persian-speaking community.
I saw a part of the discussion module that needs to be converted to Jalali.
![1](https://user-images.githubusercontent.com/66952858/147750121-cd3d0e3f-8ced-4a9e-a889-d43d03cccfbb.PNG)

**Comment by saeed-raeisi** [comment]
Persian :
چه اقدامی انجام داده اید؟
 js این بخش به کمک 
تبدیل می شود 

English :
What did you do? This section is converted with the help of js

**Comment by saeed-raeisi** [comment]
Persian :

> خب اگر اقدامی انجام ندادید اطلاع بدید تا راهنمایی کنم 
> استفاده و نیاز شما از نرم افزار مدیریت منابع سازمانی چیست ؟
> شاید بتوانم روی یکی از سرور ها یک دیتابیس در اختیار شما قرار بدهم تا بررسی کنید
> اگر برای سازمان یا شرکتی میخواید الان شرکت های زیادی در حال کار روی این پروژه هستن

English :
Well, if you have not taken any action, let me know so I can help
What is your use and need of erp? Maybe I can prepare an instance for you to use.

[tashilgostar](https://www.tashilgostar.com/) فوق العاده هستن و باعث افتخار ایران
They are wonderful and make Iran proud
[namaadiran](https://www.namaadarya.com/)  گروه بسیار بزرگی هستن 
They are a very large group
[kenevist](https://www.kenevist.ir/) عالی دارن پیش میرن
They are doing great
[samim](https://www.odoo.ir/) فعالیت مشخصی ندارن
They do not have a specific activity
[asd](http://www.asd.ir:8069/)   -> [godoo](http://www.godoo.ir/) تیم حرفه ای ولی فعالیت مشخص نیست
They do not have a specific activity

@mrr-r
Good luck-موفق باشید

**Comment by mrr-r** [comment]
آقای رئیسی من روی اودوو تازه نصب شده بدون هیچ ماژول اضافه ای تست کردم ولی نتیجه همان شد و تقویم تبدیل نشد.
در ضمن ممنون بابت سایت های که معرفی کردید اما هیچ کدام از آنها به درستی و صداقت شما در کار نیستند و خواهان پیشرفت دیگران در علم نیستند.
درباره این سوال هم که پرسیدید استفاده و نیاز شما از نرم افزار مدیریت منابع سازمانی چیست ؟ باید بگم که مثل اینه که همه برگه های بهم ریخته خود را داخل یه پوشه مرتبط بچینی و هر وقت بخوای بری سراغش.
درباره این پرسش هم که پرسیدید شاید بتوانم روی یکی از سرور ها یک دیتابیس در اختیار شما قرار بدهم تا بررسی کنید. باید بگم که من فقط روی لوکال کار می کنم.
باز هم سپاس از شما که یه کاری برای بنده و فارسی زبان ها و کسانی که از تاریخ خورشیدی استفاده می کنند انجام می دید.
