### ISSUE TITLE
در اودوو اینترپرایس

### ISSUE THREAD

**Issue by mrr-r** [parodoo/parOdoo#18]
![1](https://user-images.githubusercontent.com/66952858/144994611-fdd9de1b-81e8-4133-8177-cdde83f815d3.PNG)
![2](https://user-images.githubusercontent.com/66952858/144994637-917de4b6-5e50-4136-9aca-c17795d2877f.PNG)
در این دو قسمت از اودوو اینترپرایس تاریخ ها به میلادی هست کسی می تونه کمک کنه برای تبدیل آنها به خورشیدی.
در ضمن بنده ماژول های پولی زیادی دارم که می تونم با کسی که همکاری کنه به اشتراک بگذارم.
با سپاس!

**Comment by MortezaMohebi** [comment]
please share the view of this model

**Comment by mory1376** [comment]
چرا نمیذاری خب مگه کمک نمیخواستی

**Comment by saeed-raeisi** [comment]
Hello
About publishing modules
Keep in mind that you are infringing on a license, and this is not morally correct

About the date:
date of these pages
In fact, one of the ways to print previews is to use a database-side tool, and the next way is to override the render functions of these pages.
