### ISSUE TITLE
باز هم در قسمت ماژول بحث

### ISSUE THREAD

**Issue by mrr-r** [parodoo/parOdoo#20]
در این بخش از ماژول (بحث) هم تاریخ به خورشیدی بر نمیگردد:

![12](https://user-images.githubusercontent.com/66952858/158196377-75280f37-6784-40f8-b571-55185777ca52.PNG)

من فکر می کنم که ایراد در اینجا رخ می دهد:

odoo/addons/mail/static/src/components/message/message.js

در این دستور در سطر 265 اگر اشتباه نکنم:

    get trackingValues() {
        return this.message.tracking_value_ids.map(trackingValue => {
            const value = Object.assign({}, trackingValue);
            value.changed_field = _.str.sprintf(this.env._t("%s:"), value.changed_field);
            if (value.field_type === 'datetime') {
                if (value.old_value) {
                    value.old_value =
                        moment.utc(value.old_value).local().format('LLL');
                }
                if (value.new_value) {
                    value.new_value =
                        moment.utc(value.new_value).local().format('LLL');
                }
            } else if (value.field_type === 'date') {
                if (value.old_value) {
                    value.old_value =
                        moment(value.old_value).local().format('LL');
                }
                if (value.new_value) {
                    value.new_value =
                        moment(value.new_value).local().format('LL');
                }
            }
            return value;
        });
    }

**Comment by saeed-raeisi** [comment]
سلام 
این مورد به نظرم بهتر 
با پچ کردن **moment.js** به طور **کامل** تقویم شمسی رو جایگزین کنید
اما پچ کردن یه کتابخانه استاندارد مانع آپگرید کردن می‌شه و قفل می‌کنه سیستم رو به همین دلیل در اودو پذیزفته نخواهد شد
_(نقل قول از اقای ملکی نژاد توسعه دهنده اودو در شرکت اودو مشغول به کار هستن)_

برای همین در حال بررسی راهی هستیم تا خود **اودو** تقویم شمسی اضافه کند.

**Comment by saeed-raeisi** [comment]
[tashilgostar](https://www.tashilgostar.com/)
[namaadiran](https://namaadiran.com/)
[kenevist](https://www.kenevist.ir/)
[asd](http://www.asd.ir/)
[odooers](https://odooers.ir/)
[sarmadsoft](https://sarmadsoft.ir/)
[meftah](https://meftah.com/)
[emisaco](https://www.emisaco.com/)
[qeshmsoft](https://qeshmsoft.com/)
[akamnet](https://akamnet.com/)
[viraweb123](https://viraweb123.ir/)
[artarad](https://artarad.ir/)
[rainesh ](https://rainesh.org/)
[drshahbazi](https://drshahbazi.ir/)
[rashano](https://rashano.com/)
[sepaanta](https://sepaanta.com/)

 البته اگر شرکت های فعال در زمینه اودو همکاری کنند این موضوع سریع تر به نتیجه مطلوب خواهد رسید 
 اودو بالای 50 ماژول برای بومی سازی نیاز دارد و تقویم شروع این راه است
 موارد قانونی ایران و... که در [وبلاگ فادو](https://fadoo.ir/blog/odoo-1/odoo-iran-1) کاملا توضیح داده شده است.

**Comment by mrr-r** [comment]
> سلام این مورد به نظرم بهتر با پچ کردن **moment.js** به طور **کامل** تقویم شمسی رو جایگزین کنید اما پچ کردن یه کتابخانه استاندارد مانع آپگرید کردن می‌شه و قفل می‌کنه سیستم رو به همین دلیل در اودو پذیزفته نخواهد شد _(نقل قول از اقای ملکی نژاد توسعه دهنده اودو در شرکت اودو مشغول به کار هستن)_
> 
> برای همین در حال بررسی راهی هستیم تا خود **اودو** تقویم شمسی اضافه کند.

سلام جناب آقای رئیسی
ممنون می شم بگید که شما از کدام پچ برای مامنت استفاده کردید چون کتابخانه‌های زیادی در این مورد هستند مانند:

https://www.npmjs.com/package/jalali-moment
https://github.com/jalaali/moment-jalaali
و موارد دیگر.

لطفاً لینک کتابخانه یا اگر شخصاً بصورت دستی تغییر دادید لینک فایل رو به اشتراک بگذارید.
باز هم سپاس!

**Comment by saeed-raeisi** [comment]
> > سلام این مورد به نظرم بهتر با پچ کردن **moment.js** به طور **کامل** تقویم شمسی رو جایگزین کنید اما پچ کردن یه کتابخانه استاندارد مانع آپگرید کردن می‌شه و قفل می‌کنه سیستم رو به همین دلیل در اودو پذیزفته نخواهد شد _(نقل قول از اقای ملکی نژاد توسعه دهنده اودو در شرکت اودو مشغول به کار هستن)_
> > برای همین در حال بررسی راهی هستیم تا خود **اودو** تقویم شمسی اضافه کند.
> 
> سلام جناب آقای رئیسی ممنون می شم بگید که شما از کدام پچ برای مامنت استفاده کردید چون کتابخانه‌های زیادی در این مورد هستند مانند:
> 
> https://www.npmjs.com/package/jalali-moment https://github.com/jalaali/moment-jalaali و موارد دیگر.
> 
> لطفاً لینک کتابخانه یا اگر شخصاً بصورت دستی تغییر دادید لینک فایل رو به اشتراک بگذارید. باز هم سپاس!

سلام دوست عزیز
شرمنده من اسم شریفتون نمیدونم 
https://github.com/jalaali/moment-jalaali/blob/master/build/moment-jalaali.js
دقیقا از همین فایل استفاده کنید 
```
<xpath expr="//script[@src='/web/static/lib/moment/moment.js']" position="after">
    <t t-if="request and request.env.lang == 'fa_IR'">
        <script type="text/javascript" src="/[Module-Name]/static/lib/moment-jalaali/moment-jalaali.js"/>
    </t>
</xpath>
```

**Comment by mrr-r** [comment]
سلام آقای مهندس رئیسی
من الان دارم از ماژول po_persian_calendar استفاده می کنم که خودش این کتابخانه را پچ کرده است.
من با استفاده از این ماژول این خطا رو در بخش "ماژول بحث وگفتگو" دارم.
شاید من منظور شما را خوب درک نکرده‌ام اگر چنین است خواهش می کنم راهنمایی فرمایید.
با سپاس

**Comment by saeed-raeisi** [comment]
> سلام آقای مهندس رئیسی من الان دارم از ماژول po_persian_calendar استفاده می کنم که خودش این کتابخانه را پچ کرده است. من با استفاده از این ماژول این خطا رو در بخش "ماژول بحث وگفتگو" دارم. شاید من منظور شما را خوب درک نکرده‌ام اگر چنین است خواهش می کنم راهنمایی فرمایید. با سپاس

سلام 
ببینید کاری که باید انجام شود در واقع تغییر فرمت تاریخ است و همچنین استفاده از  local جلالی

'YYYY/M/D':"jYYYY/jM/jD"

تیم فادو به زودی نسخه رایگان تقویم شمسی منتشر میکند
تنها مواردی که طبق توافق تیم در ماژول نخواهد بود 

1. اصلاح fullcalendar (اپدیت [jquery datepicker](https://jqueryui.com/datepicker/) )
2.  اصلاح search_utils (رنج تاریخ در فیلتر و دسته بندی )

این موراد مستندات از طرف ما ارائه خواهد شد تا بقیه دوستان به صورت متن باز توسعه بدهند (مستندات در گروه خصوصی تلگرام )
سایر مواردی که در ماژول قرار دارد اصلاحات استایل برای rtl است 
مواردی مثل colorpicker - address_format
