### ISSUE TITLE
صدور فاکتور به صورت pdf

### ISSUE THREAD

**Issue by mrr-r** [parodoo/parOdoo#4]
با درود و خسته نباشید به شما دوست گرامی،
سپاس از ماژول که به اشتراک گذاشته اید.
من یک خواهش داشتم اونم اینه که در هنگام صدور فاکتور به صورت pdf تاریخ میلادی می باشد و اگر امکانش هست این ایراد رو برطرف کنید.
باز هم سپاس گذارم!
من این ایراد رو با ساخت چند ماژول برطرف کردم می تونید به صفحه بنده بروید و دانلود و تست کنید

**Comment by BabakMahmoudi** [comment]
سلام ممنون
روی این موضوع کار میکنیم.
اگر بخواهید مبتوانید با @pariamahmoudi تماس بگیرید. 
میتواند برای شما مشکل را با یک گزارش سفارشی حل کند

**Comment by mrr-r** [comment]
سلام آقای محمودی سپاس گذار می شم اگه اون گزارش سفارشی که می گید رو اینجا به اشتراک بذارید مرسی از وقتی که میذارید..

**Comment by ahmadzadeh110** [comment]
> با درود و خسته نباشید به شما دوست گرامی، سپاس از ماژول که به اشتراک گذاشته اید. من یک خواهش داشتم اونم اینه که در هنگام صدور فاکتور به صورت pdf تاریخ میلادی می باشد و اگر امکانش هست این ایراد رو برطرف کنید. باز هم سپاس گذارم! من این ایراد رو با ساخت چند ماژول برطرف کردم می تونید به صفحه بنده بروید و دانلود و تست کنید

به نام خدا
با سلام و احترام.
ضمن تشکر بابت اصلاح تاریخ در نسخه چاپی پی دی اف
مشکلی که وجود دارد این است که وقتی تاریخ سامانه را به میلادی بر می گردانیم باز در پی دی اف تاریخ شمسی چاپ می شود.
