### ISSUE TITLE
تاریخ اشتباه در بعضی از روزها

### ISSUE THREAD

**Issue by faryadmh** [parodoo/parOdoo#7]
با سلام وخسته نباشید
ضمن تشکر از پروژه ی خوبتان
یه مشکلی که داره اینه در بعضی از تاریخ ها روزها بعد از ذخیر شده عوض میشند 
مثلا برای تاریخ اول بهمن 99 بعد از ذخیره به تاریخ سال 1611 تبدیل میشه
توی بعضی تاریخ های دیگه این مشکل هست
و نکته ی بعدی اینکه در دیت ها مشکل هست و در دیت تایم  ها مشکل نیست
ممنون

**Comment by BabakMahmoudi** [comment]
از توجه شما ممنونم.
مشکل اول بهمن را بررسی میکنم.
اما درست متوجه نشدم فقط در فیلدهای "دیت" مشکل هست و در "دیت تایم" مشکلی نیست؟

**Comment by faryadmh** [comment]
سلام مجدد منظورم این بود که توی فرم های اودو اگه ازDatetime picker استفاده شود تاریخ اول بهمن مشکلی نداره ولی اگه از Datepickerاستفاده بشه مشکل داره.
-------- Original message --------From: BabakMahmoudi <notifications@github.com> Date: 23/01/2021  19:20  (GMT+03:30) To: parodoo/parOdoo <parOdoo@noreply.github.com> Cc: faryadmh <hassanzadeh2119@gmail.com>, Author <author@noreply.github.com> Subject: Re: [parodoo/parOdoo] تاریخ اشتباه در بعضی از روزها (#7) 

از توجه شما ممنونم.

مشکل اول بهمن را بررسی میکنم.

اما درست متوجه نشدم فقط در فیلدهای "دیت" مشکل هست و در "دیت تایم" مشکلی نیست؟

**Comment by faryadmh** [comment]
سلام وقت شما بخیر .
روی این مورد به نتیجه ای نرسیدین؟

**Comment by BabakMahmoudi** [comment]
The issue is now fixed in
#11
