### ISSUE TITLE
نمودارها

### ISSUE THREAD

**Issue by mrr-r** [parodoo/parOdoo#8]
جناب آقای محمودی اگه بتونید روی بخش نمودارها هم کار کنید ممنون می شم
![2](https://user-images.githubusercontent.com/66952858/110497473-b79bda80-810b-11eb-8b29-5b0e2ca746a5.PNG)

**Comment by saeed-raeisi** [comment]
اگر یه ویجت یا کامپوننت جدید نوشته بشه و جایگزین بشه بهتره 
شما علاقه مند به همکاری هستید؟

**Comment by saeed-raeisi** [comment]
برای مثال حسابداری cybrosys 
نمودار های خوبی به بخش حسابداری اضافه کرده است
https://apps.odoo.com/apps/modules/14.0/base_accounting_kit/
https://www.cybrosys.com/odoo-apps/odoo-13-full-accounting-kit

**Comment by saeed-raeisi** [comment]
https://github.com/FadooIR/l10n-iran
https://github.com/OCA/l10n-iran
This is done here

All odoo labels use the Babylon Library

Solution one:
Localization of Babylon for Iran

Solution two:
Use jadatetime and inherit label creation functions

تمام لیبل های اودو از کتابخانه بابل استفاده میکنند

راه حل یک :
 بومی سازی بابل برای ایران

راه حل دو : 
استفاده از jadatetime 
و ارث بری از توابع ایجاد کننده لیبل
